### ISSUE TITLE
activesupport 3.0

### ISSUE THREAD

**Issue by ghost** [rugui/rugui#28]
Rugui 1.5.4 doesn't work with activesupport 3.0:

```
/home/sebn/.rvm/gems/ruby-1.8.7-p302@gnome-tv/gems/rugui-1.5.4/lib/rugui/initializer.rb:76:in `set_autoload_paths': undefined method `load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
from /home/sebn/.rvm/gems/ruby-1.8.7-p302@gnome-tv/gems/rugui-1.5.4/lib/rugui/initializer.rb:48:in `process'
from /home/sebn/.rvm/gems/ruby-1.8.7-p302@gnome-tv/gems/rugui-1.5.4/lib/rugui/initializer.rb:26:in `send'
from /home/sebn/.rvm/gems/ruby-1.8.7-p302@gnome-tv/gems/rugui-1.5.4/lib/rugui/initializer.rb:26:in `run'
...
```

ActiveSupport::Dependencies#load_paths was renamed to #autoload_paths in activesupport 3.0:

https://github.com/rails/rails/blob/master/activesupport/CHANGELOG#L29

The following gemspec requirement should work:

```
s.add_runtime_dependency(%q<activesupport>, ["~> 2.3"])
```

**Comment by ghost** [comment]
Fixed here:

https://github.com/sebn/rugui/commit/ef352effc0102dacec45911bd6a11ce9808aea9c

But this would make rugui depend on activesupport >= 3.0

**Comment by ghost** [comment]
Actually, activesupport >= 2.3.9 should work.

**Comment by vicentemundim** [comment]
I've just pushed a patch that will address this. Just update your RuGUI to 1.6.0.
