### ISSUE TITLE
Rake run doesn't work

### ISSUE THREAD

**Issue by fedesilvaponte** [rugui/rugui#31]
This is the error I get after creating a new app using rugui and tried to run it:

-> rake run
(eval):1: warning: redefining `object_id' may cause serious problems
(eval):1: warning: redefining`**send**' may cause serious problems
rake aborted!
undefined method `class_inheritable_accessor' for RuGUI::BaseController:Class

(See full trace by running task with --trace)

**Comment by vicentemundim** [comment]
Hi, you are probably using RuGUI with ActiveSupport gem >= 3.1.0, which
deprecated (removed in 3.2.0) the `class_inheritable_accessor`. Try to
uninstall the activesupport gem and instal version 3.0.12.

gem uninstall activesupport
gem install activesupport -v 3.0.12

If the problem still happens, please send a list of your installed gems.

Cheers

On Sun, Mar 18, 2012 at 5:25 PM, fedesilvaponte <
reply@reply.github.com

**Comment by fedesilvaponte** [comment]
Thanks, but that didn't solve it, here's the output:

-> rake run
(eval):1: warning: redefining `object_id' may cause serious problems
(eval):1: warning: redefining`**send**' may cause serious problems
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /home/fede/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/rdoctask.rb
rake aborted!
can't convert Pathname into String

Tasks: TOP => run
(See full trace by running task with --trace)

**Comment by lcezermf** [comment]
Hi, I have the same problem.

I created a new app (my first app with ruGUI), but when I tried to ran the command to start my app, my console show this :

cezinha@cezinha-Positivo-Mobile:~/ProjetosRails/RuGUI/HelloWorld$ ./bin/HelloWorld
(eval):1: warning: redefining `object_id' may cause serious problems
(eval):1: warning: redefining`**send**' may cause serious problems
/home/cezinha/.rvm/gems/ruby-1.9.2-p290@rails3/gems/rugui-1.6.0/lib/rugui/initializer.rb:89:in `eval': can't convert Pathname into String (TypeError)

I'm using Ruby 1.9.2

**Comment by vicentemundim** [comment]
Hi, I haven't tested RuGUI with Ruby 1.9, since it was not released when
RuGUI was first developed. You can try to use ruby 1.8.7. This error should
be simple to fix though, I'll take a look at it later.

Cheers,

**Comment by lcezermf** [comment]
hm, ok I will try with ruby 1.8.7

**Comment by lcezermf** [comment]
I try to use RuGUI w/ ruby 1.8.7, but when a build my app and do the command : rake run to start my app my prompt show this :

cezinha@cezinha-Positivo-Mobile:~/ProjetosRails/RuGUI/HelloWorld$ rake run
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /home/cezinha/.rvm/gems/ruby-1.8.7-p357@rails304/gems/rake-0.9.2.2/lib/rake/rdoctask.rb
2012-08-29 10:18:27 (INFO) (RuGUI::Initializer) Starting RuGUI application with development environment...
rake aborted!
no such file to load -- libglade2

Tasks: TOP => run
(See full trace by running task with --trace)
cezinha@cezinha-Positivo-Mobile:~/ProjetosRails/RuGUI/HelloWorld$ rake run --trace
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /home/cezinha/.rvm/gems/ruby-1.8.7-p357@rails304/gems/rake-0.9.2.2/lib/rake/rdoctask.rb
*\* Invoke run (first_time)
*\* Execute run
2012-08-29 10:18:39 (INFO) (RuGUI::Initializer) Starting RuGUI application with development environment...
rake aborted!
no such file to load -- libglade2

apparently my app doesn't find the libglade2, how can I fix it?

**Comment by vicentemundim** [comment]
Yes, you would need to install libglade2, which is now outdated. Yesterday
I started to update RuGUI code so that it uses bundler and newer libs, like
Gtk::Builder. There are still some issues that I'm fixing, but I think that
by the end of the week I'll be releasing a beta version.

In the meantime, you could try to install libglade2, what OS are you using?

**Comment by lcezermf** [comment]
hm ok, I can wait for the new update to start to use RuGUI, for the time being I will code Gtk manually.
I'm using Ubuntu 11.04 with Ruby 1.8.7

**Comment by vicentemundim** [comment]
Hi,

I've just released a beta version of RuGUI that works in Ruby 1.9.3, with
support to bundler, and updated bindings. I've added some instructions on
how to use RuGUI on Mac OS X, but still have to add instructions for Linux
and Windows. It shouldn't be hard though, given you already have GTK
installed everything should be fine.

Here is the new README:

https://github.com/rugui/rugui/blob/master/README.rdoc

If you find any issues feel free to post them here.

Thanks

**Comment by lcezermf** [comment]
Hi, thanks for the update man, I will test the new version soon :)

**Comment by drfrog666** [comment]
hi
love this concept!
cant seem to get it to run either, im on ruby 1.9 
when i try to run i got the class accessor issue

reinstalled activesupport  w lower versionthen get cant convert pathname to string

please let me know what i should do to get this running very interested

**Comment by boris-s** [comment]
Hi, 6 months after, installing via "gem install", on ruby 1.9.3, I ran into the very same problem:
undefined method 'inheritable_class_accessor'

I am not really so knowledgeable about ActiveSupport, but if they decided to deprecate and
remove that method, and you want to continue using it in rugui, then make it part of rugui
please. Or comply with the reasoning of the ActiveSupport team (they must have had their
reasons for removing it) and instead of using the obsolete method, do things the new way
(whathever the new way is).

As for the new README file, when I try "bundle install" in the end, it says
"Could not locate Gemfile". What should I do?

**Comment by vicentemundim** [comment]
Just changed the README, when installing you must specify the version because it is a beta version:

```
gem install rugui -v 2.0.0.beta2
```

**Comment by boris-s** [comment]
You are amazing. I thought my comment would just get ignored :-). Your line worked for me. I no longer see the complaint about 'inheritable_class_accessor'. But I still have the other problem. Normally I create gems on my machine with `bundle gem my_app`, and I know what to do to make them work. But when I create a Rugui app with `rugui my_app`, cd into it and run `bundle install`, as prescribed in README, it says "Could not locate Gemfile", and I do not know what to do. Am I doing something wrong?

**Comment by vicentemundim** [comment]
That's weird, have you tried creating a new RuGUI app after installing 2.0.0.beta2 and see if it works? Could you check the RuGUI version using `rugui -v`? Is there a Gemfile in the generated application?

**Comment by boris-s** [comment]
`rugui -v` output: RuGUI 2.0.0.beta2
Contents of the directory (simple_calculator example project that I yearned to try): Apart from the usual directories, 3 files: Rakefile, README and Gemfile.tt. Still, this Gemfile.tt does not satisfy `bundle install`. Btw. my bundler version is 1.1.3, ruby version is 1.9.3p194.

**Comment by vicentemundim** [comment]
Try creating a `Gemfile` in the root of the generated project with these contents and see if it works:

``` ruby
source "http://rubygems.org"

# RuGUI gem
gem 'rugui', '~> 2.0.0.beta'

# GTK ruby bindings
gem 'gtk2'

# Uncomment this if you want to debug applications
# gem 'debugger'

group :test do
  gem 'rspec', '>= 2.11.0'
end
```

**Comment by boris-s** [comment]
Vincente, thank you! I want to kiss you all over! You made it run for me :-))) Hooray!!! Hello world button appeared!!! Now lemme see your DSL :-))))

**Comment by marianeichholz** [comment]
Amazing. The 2.0.0.beta2 works really nice. The approach to GUI programming this way _really_ appeals to me. It's just really hard to tap into the details of the framework, and - well - the changes of the framework, as it evolves.

I'd like to rework some of the master applications, like simple_calculator, or the hanoi-rugui program.
Unfortunately they are rugui 1.6 and severely incompatible to the current state of the art.

Is there some sort of migration guide, as for the major rails incarnations?

Should we make this a new issue? As far as I could see, there are some sub issues:
- the ressources somehow changed from "glade" to "xml", with incompatible XML containers ("unsupported widget"). Is there a way to port them?
- Even with a Gemfile, "redefining `object_id' may cause serious problems" persists.
- Some "Glade-for-Dummies" mini-howto would be really nice, because I have no idea how to start and maintain an interface-definitions (never worked with glade in my C-GTK+-days).

I am really reluctand to backstepping to something "dead" as Ruby 1.8.7 or Active\* < 3.2, so there probably some aspiring developers have the same chicken-egg-problem with the sample applications.

I'd probably port-and-fork the applications myself, document the necessary steps and contribute that back, because I really like the RuGui approach.

Chapeau for the idea and for the beta2-Code! Let it live! - Marian

**Comment by vicentemundim** [comment]
Hi,

The 2.x version will probably only support ruby 1.9.3 and ActiveSupport >= 3.2, so you're right about backstepping to  older versions of ruby and ActiveSupport.

The goal of this major version bump would be to be able to use Bundler, which seems to work right now, and support the new RubyGTK and ruby QT bindings. I had some issues with the QT bindings, I couldn't compile it in Mac OS.

As for glade, its new version 3.0 has changed the resource file from `.glade` to `.xml`. It has also changed the GTK API, and so it is incompatible with older versions.

The issue with object_id is something that we'll definitively need to look at. This is related to the Observer pattern implementation of models. This will require some redesign of the pattern, but I have some ideas in mind.

Creating those issues would really help us keep track of the progress, and prioritize what needs to be done. If you want, go ahead and create them!

**Comment by boris-s** [comment]
Hi everyone, I've been keeping rugui on the back burner so far, since I'm still in the design phase of my app basic functionality, but Github has notified me by email, so just let me say: I hope that rugui will work fully with Ruby 2.0, because I already switched to it.
